### ISSUE TITLE
Status for “Review Queue” and “Feedback Queue” 

### ISSUE THREAD

**Issue by warneboldt** [pathwaysmedical/frasernw#109]
Add an extra field to the review queue and feedback queue, similar to “Admin Only Notes” for specialists and clinics, so that administrators can make notes on the status of these items

**Comment by warneboldt** [comment]
Please also display the division(s) of the user who left the feedback / review queue item in the admin display of all feedback / review queue items.

**Comment by KelseyDH** [comment]
#105 reference similar issue

**Comment by KelseyDH** [comment]
@bgracie  Can we safely say this issue is finished now with the new History feature you built?

**Comment by KelseyDH** [comment]
Closed due to history feature being built.
