### ISSUE TITLE
Losing clinic location info

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#150]
To reproduce:
- edit clinic using secret edit link
- review changes
- location info will be gone

**Comment by bgracie** [comment]
looks like the review queue js is mistakenly switching locations to 'not used'..

**Comment by bgracie** [comment]
And this is only because there are no hospitals/cities provided to the form when there is no current user (secret edit link)

https://github.com/pathwaysmedical/frasernw/blame/master/app/views/clinics/_form.html.haml#L338

This problem also likely applies to specialists and offices, since they have current_user_divisions.

**Comment by bgracie** [comment]
related to:

CR Item #10 Modify the review queue survey
- Modify the 'areas of specialty' and & 'location addresses' fields in survey sent out via the review queue.

**Comment by bgracie** [comment]
Tracy reported the following:
- clinic currently has a standalone address
- someone edited
--> review queue form has location as 'not used', only missing 'city' is highlighted; the rest of the address info is gone without being highlighted...

**Comment by bgracie** [comment]
Reproduced
- edited a clinic via secret edit link
- city was gone, though address wasn't...
- save that edit
- in review queue, both city and address were gone

**Comment by KelseyDH** [comment]
We will need to look into this issue from a few places where clinics get edited:

1. via a clinic secret edit link (i.e., `current_user_divisions` is nil)

2. via a user clicking *review* because they have rights to edit that clinic

3. via admins reviewing/approving changes occurring from 1 & 2

4. via admins editing clinics independently on their own

 1 and 2 should change so that no address is shown anymore, and gets replaced with a text box asking for address updates.  `@is_review` and `@is_rereview` are two instance variable booleans in Clinics controller that define some of this behaviour.

**Comment by bgracie** [comment]
Specs:

- [ ] Story 1:
- user edits clinic via secret edit link sent to them by admin
- 'specializations' and 'address'/'hospital' fields are disabled
- there are comment boxes below these fields where the user can note changes
- the user notes changes
- admin reviews the changes
- the comment boxes are highlighted
- admin makes changes in the review step
- admin deletes the comments
- admin accepts the changes
- admin re-reviews the changes
- comments are there, and highlighted

- [ ]Story 2:
- same as above, except user is logged in, editing their own clinic

- [ ] Story 3:
- same as Story 1, but for specialists

- [ ]Story 4
- same as Story 2, but for specialists

**Comment by bgracie** [comment]
PR: https://github.com/pathwaysmedical/frasernw/issues/150

**Comment by bgracie** [comment]
*Testing locally, 1:30 PM June*

**Specs:**

- [ ] Story 1:
- user edits clinic via secret edit link sent to them by admin
- 'specializations' and 'address'/'hospital' fields are disabled
- there are comment boxes below these fields where the user can note changes
- the user notes changes
- admin reviews the changes
- the comment boxes are highlighted
- admin makes changes in the review step
- admin deletes the comments
- admin accepts the changes
- changes are reflected in the clinics/show page
- admin re-reviews the changes
- comments are there, and highlighted

- [ ] Story 2:
- same as above, except user is logged in, editing their own clinic

- [ ] Story 3:
- admin edits a clinic
- results are the same as before these changes

- [ ] Story 4:
- user edits specialist via secret edit link sent to them by admin
- 'specializations' and 'office' fields are disabled
- there are comment boxes below these fields where the user can note changes
- the user notes changes
- admin reviews the changes
- the comment boxes are highlighted
- admin makes changes in the review step
- admin deletes the comments
- admin accepts the changes
- changes are reflected in the specialists/show page
- admin re-reviews the changes
- comments are there, and highlighted

- [ ] Story 5:
- same as above, except user is logged in, editing their own specialist

- [ ] Story 6:
- admin edits a specialist
- results are the same as before these changes

**Comment by bgracie** [comment]
Encountered strange behaviour testing Story #2 at the rereview step
- location information that had been in the 'location 1' slot was gone
- blank fields with 'was_blank' notations
- in location 9, blank fields with 'was <actual previous value>' notations....

**Comment by bgracie** [comment]
Attempted to reproduce issue with Story 2 with another clinic
- actual persisted clinic data and review object look correct at all stages
- however, the form at the rereview step was still missing location data

**Comment by bgracie** [comment]
Seems to be fine with a third clinic, though this clinic has all 8 locations.  Perhaps this is relevant?

**Comment by bgracie** [comment]
Fourth clinic with one location turns out to be fine..

**Comment by bgracie** [comment]
Identified the problem as being caused by different 'versions' of the formdata  being in different orders 

*Testing locally, 1:30 PM June 23*
**Specs:**

- [ ] Story 1:
- user edits clinic via secret edit link sent to them by admin
- 'specializations' and 'address'/'hospital' fields are disabled
- there are comment boxes below these fields where the user can note changes
- the user notes changes
- admin reviews the changes
- the comment boxes are highlighted
- admin makes changes in the review step
- admin deletes the comments
- admin accepts the changes
- changes are reflected in the clinics/show page
- admin re-reviews the changes
- comments are there, and highlighted

- [ ] Story 2:
- same as above, except user is logged in, editing their own clinic

- [ ] Story 3:
- admin edits a clinic
- results are the same as before these changes

- [ ] Story 4:
- user edits specialist via secret edit link sent to them by admin
- 'specializations' and 'office' fields are disabled
- there are comment boxes below these fields where the user can note changes
- the user notes changes
- admin reviews the changes
- the comment boxes are highlighted
- admin makes changes in the review step
- admin deletes the comments
- admin accepts the changes
- changes are reflected in the specialists/show page
- admin re-reviews the changes
- comments are there, and highlighted

- [ ] Story 5:
- same as above, except user is logged in, editing their own specialist

- [ ] Story 6:
- admin edits a specialist
- results are the same as before these changes

**Comment by bgracie** [comment]
ReReview highlighting is broken for clinic 403 b.c. an 'update_referral_form' form was saved as a base object for a review item

**Comment by bgracie** [comment]
*Testing locally, June 24*
**Specs:**

- [ ] Story 1:
- user edits clinic via secret edit link sent to them by admin
- 'specializations' and 'address'/'hospital' fields are disabled
- there are comment boxes below these fields where the user can note changes
- the user notes changes
- admin reviews the changes
- the comment boxes are highlighted
- admin makes changes in the review step
- admin deletes the comments
- admin accepts the changes
- changes are reflected in the clinics/show page
- admin re-reviews the changes
- comments are there, and highlighted

- [ ] Story 2:
- same as above, except user is logged in, editing their own clinic

- [ ] Story 3:
- admin edits a clinic
- results are the same as before these changes

- [ ] Story 4:
- user edits specialist via secret edit link sent to them by admin
- 'specializations' and 'office' fields are disabled
- there are comment boxes below these fields where the user can note changes
- the user notes changes
- admin reviews the changes
- the comment boxes are highlighted
- admin makes changes in the review step
- admin deletes the comments
- admin accepts the changes
- changes are reflected in the specialists/show page
- admin re-reviews the changes
- comments are there, and highlighted

- [ ] Story 5:
- same as above, except user is logged in, editing their own specialist

- [ ] Story 6:
- admin edits a specialist
- results are the same as before these changes

**Comment by bgracie** [comment]
Issue w/ story# 2: disabled inputs aren't saved as base_object formdata

**Comment by bgracie** [comment]
*Testing on Test*
**Specs:**

- [ ] Story 1:
- user edits clinic via secret edit link sent to them by admin
- 'specializations' and 'address'/'hospital' fields are disabled
- there are comment boxes below these fields where the user can note changes
- the user notes changes
- admin reviews the changes
- the comment boxes are highlighted
- admin makes changes in the review step
- admin deletes the comments
- admin accepts the changes
- changes are reflected in the clinics/show page
- admin re-reviews the changes
- comments are there, and highlighted

- [ ] Story 2:
- same as above, except user is logged in, editing their own clinic

- [ ] Story 3:
- admin edits a clinic
- results are the same as before these changes

- [ ] Story 4:
- user edits specialist via secret edit link sent to them by admin
- 'specializations' and 'office' fields are disabled
- there are comment boxes below these fields where the user can note changes
- the user notes changes
- admin reviews the changes
- the comment boxes are highlighted
- admin makes changes in the review step
- admin deletes the comments
- admin accepts the changes
- changes are reflected in the specialists/show page
- admin re-reviews the changes
- comments are there, and highlighted

- [ ] Story 5:
- same as above, except user is logged in, editing their own specialist

- [ ] Story 6:
- admin edits a specialist
- results are the same as before these changes
