### ISSUE TITLE
ActiveRecord::StatementInvalid in pathways:recache:specialists

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#170]
## New exception in pathways

**ActiveRecord::StatementInvalid** in **pathways:recache:specialists**
PG::ConnectionBad: PQconsumeInput() SSL SYSCALL error: Connection timed out
: SELECT &quot;specialists&quot;.* FROM &quot;specialists&quot;  ORDER BY specialists.lastname, specialists.firstname

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/5583dbdbf1726aac68499e20?event_id=5583dbdb861707d66f08f0df)

## Stacktrace

    lib/tasks/recache.rake:55 - block (3 levels) in &lt;top (required)&gt;

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/5583dbdbf1726aac68499e20?event_id=5583dbdb861707d66f08f0df)

**Comment by KelseyDH** [comment]
Rake task timeout, doesn't look like bug.  Will need to get bugsnag to stop adding these.
