### ISSUE TITLE
ActiveRecord::StatementInvalid in pathways:recache:sc_categories

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#171]
## New exception in pathways

**ActiveRecord::StatementInvalid** in **pathways:recache:sc_categories**
PG::ConnectionBad: PQconsumeInput() SSL SYSCALL error: Connection timed out
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = &#x27;&quot;sc_categories&quot;&#x27;::regclass
               AND a.attnum &gt; 0 AND NOT a.attisdropped
             ORDER BY a.attnum

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/558680fff1726aac684ef3cd?event_id=558680ff8979cd0f32183864)

## Stacktrace

    lib/tasks/recache.rake:151 - block (4 levels) in &lt;top (required)&gt;
    lib/tasks/recache.rake:150 - each
    lib/tasks/recache.rake:150 - block (3 levels) in &lt;top (required)&gt;

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/558680fff1726aac684ef3cd?event_id=558680ff8979cd0f32183864)

**Comment by KelseyDH** [comment]
pretty sure this is just caused by us hitting `http` and `https` together.

**Comment by KelseyDH** [comment]
If we encounter this on Produciton rather than staging we'll look into it.
