### ISSUE TITLE
ActiveRecord::StatementInvalid in jobs:work

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#173]
## New exception in pathways

**ActiveRecord::StatementInvalid** in **jobs:work**
PG::UndefinedTable: ERROR:  relation &quot;delayed_jobs&quot; does not exist
LINE 1: UPDATE &quot;delayed_jobs&quot; SET &quot;locked_by&quot; = NULL, &quot;locked_at&quot; = ...
               ^
: UPDATE &quot;delayed_jobs&quot; SET &quot;locked_by&quot; = NULL, &quot;locked_at&quot; = NULL WHERE &quot;delayed_jobs&quot;.&quot;locked_by&quot; = &#x27;host:0d6ec0cb-9268-4187-9eaa-592d1b66d26d pid:3&#x27;

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/5589c763f1726aac6856ec95?event_id=5589c76367173b9273469277)

## Stacktrace

    bin/rake:37 - &lt;main&gt;

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/5589c763f1726aac6856ec95?event_id=5589c76367173b9273469277)

**Comment by KelseyDH** [comment]
test only problem
