### ISSUE TITLE
ActiveRecord::StatementInvalid in front#index

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#174]
## New exception in pathways

**ActiveRecord::StatementInvalid** in **front#index**
PG::UndefinedTable: ERROR:  relation &quot;sessions&quot; does not exist
LINE 5:              WHERE a.attrelid = &#x27;&quot;sessions&quot;&#x27;::regclass
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = &#x27;&quot;sessions&quot;&#x27;::regclass
               AND a.attnum &gt; 0 AND NOT a.attisdropped
             ORDER BY a.attnum

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/558a954df1726aac6858ea36?event_id=558a954d50e11fa63290bc62)

## Stacktrace

    lib/controller_authentication.rb:87 - store_target_location
    lib/controller_authentication.rb:61 - login_required

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/558a954df1726aac6858ea36?event_id=558a954d50e11fa63290bc62)

**Comment by KelseyDH** [comment]
test server issue, not a problem it appears on production
