### ISSUE TITLE
ActiveRecord::StatementInvalid in pathways:visit_every_page:specializations

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#175]
## New exception in pathways

**ActiveRecord::StatementInvalid** in **pathways:visit_every_page:specializations**
PG::UndefinedTable: ERROR:  relation &quot;specializations&quot; does not exist
LINE 5:              WHERE a.attrelid = &#x27;&quot;specializations&quot;&#x27;::regclas...
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = &#x27;&quot;specializations&quot;&#x27;::regclass
               AND a.attnum &gt; 0 AND NOT a.attisdropped
             ORDER BY a.attnum

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/558aa2d2f1726aac68590cb7?event_id=558aa2d2066627d217d23c97)

## Stacktrace

    lib/tasks/visit_every_page.rake:8 - block (3 levels) in &lt;top (required)&gt;

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/558aa2d2f1726aac68590cb7?event_id=558aa2d2066627d217d23c97)

**Comment by KelseyDH** [comment]
test issue too it appears
