### ISSUE TITLE
ActiveRecord::StatementInvalid in GET /

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#176]
## New exception in pathways

**ActiveRecord::StatementInvalid** in **GET /**
PG::UndefinedTable: ERROR:  relation &quot;sessions&quot; does not exist
LINE 5:              WHERE a.attrelid = &#x27;&quot;sessions&quot;&#x27;::regclass
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = &#x27;&quot;sessions&quot;&#x27;::regclass
               AND a.attnum &gt; 0 AND NOT a.attisdropped
             ORDER BY a.attnum

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/558afe5bf1726aac685a1627?event_id=558afe5bdb4eadd52b69bf5a)

## Stacktrace

    vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - async_exec
    vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163 - exec_no_cache
    vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:660 - block in exec_query

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/558afe5bf1726aac685a1627?event_id=558afe5bdb4eadd52b69bf5a)

**Comment by KelseyDH** [comment]
bugsnag sucking again
