### ISSUE TITLE
ActionView::Template::Error in user_sessions#new

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#177]
## New exception in pathways

**ActionView::Template::Error** in **user_sessions#new**
undefined method &#x60;email&#x27; for #&lt;UserSession:0x007f18a7066870&gt;

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/558b130af1726aac685a554f?event_id=558b130b6f2bbb7270bad254)

## Stacktrace

    app/views/user_sessions/new.html.haml:14 - block in _app_views_user_sessions_new_html_haml___1054486563948004259_69871928711520
    app/views/user_sessions/new.html.haml:7 - _app_views_user_sessions_new_html_haml___1054486563948004259_69871928711520

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/558b130af1726aac685a554f?event_id=558b130b6f2bbb7270bad254)

**Comment by KelseyDH** [comment]
Occurred on test server
