### ISSUE TITLE
paper trail Version serving up old #item

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#189]
in front_helper#latest_updates, paper trail has been serving up  old versions of specialist offices when we call #item.
where else in the app is this happening?

**Comment by bgracie** [comment]
regards Alanna's email: "Dr. Osamah Alenezi's Entry on Vancouver Home Page"

**Comment by bgracie** [comment]
This is still an issue.  Cause of incorrect entry for Specialist #2268 (Specialist Office #7543) on Vancouver Latest Specialist and Clinic Updates.

The problems seems to occur when:
- you load up a version's #item (current state of the record)
- you then reify the version, getting the old state of the record
--> when you refer to the item again, you'll get the old state (even if it was cloned!)

Possible explanation:
- A.R. internally caches records in an I.D. map --> one ID per record, meaning it doesn't support multiple versions floating around at the same time?
http://api.rubyonrails.org/v3.2.5/classes/ActiveRecord/IdentityMap.html

**Comment by bgracie** [comment]
solution is to dup the item:

https://github.com/airblade/paper_trail/pull/399

**Comment by KelseyDH** [comment]
https://github.com/pathwaysmedical/frasernw/commit/b483f232fde10f3dd299159b9f36077139b50c6a
