### ISSUE TITLE
changes propagating irregularly

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#191]
- new endocrinologist, Dr. Supna Sandhu, entered on July 7, but this didnt show up on the home page under "latest specialist and clinic updates" until July 10
- Internal Medicine specialist, Dr. Anita Palepu, entered on July 8, didn't show up in search box or on the Int. Med. specialty page
- same thing with David Lin, an opthamologist

**Comment by bgracie** [comment]
- couldn't find David Lin in search box when logged in as a FNW super admin
- this is expected behaviour!
- could not find David Lin in search box when logged in as Vancouver test account
- was able to find him after expanding the search, however
- also able to find him when logged in as incognito
- this leads me to believe that the issue is that a cached version of "livesearch.js" is the culprit

**Comment by bgracie** [comment]
Options to fix:
- separate variable index data from constant behaviour (data is either loaded directly to the page in a %script tag or ajax-requested)

**Comment by bgracie** [comment]
kind of weird metadata from the chrome network window:
(make up your mind!  is it cached or not?)

Status Code:200 OK (from cache)
Response Headers
cache-control:public, max-age=43200
cf-cache-status:MISS

**Comment by bgracie** [comment]
Oh, so 200 OK (from cache) means the browser didn't even try to get a fresh copy
see: http://stackoverflow.com/questions/1665082/http-status-code-200-cache-vs-status-code-304

- the 'cf-cache-status: MISS' is a part of the CACHED RESPONSE (it was a miss when the cached version was generated...)

**Comment by bgracie** [comment]
Options to fix:
1. separate variable index data from constant behaviour (data is either loaded directly to the page in a %script tag or ajax-requested)

2. serve this asset explicitly from a rails controller, and set no cache headers that way...
http://stackoverflow.com/questions/8559915/prevent-caching-of-a-single-js-file

Considerations
2) would probably be easier, but it means putting more work into an essentially dead end approach
- difficult to reason about dynamically constructed js
- can't precompile the file (--> performance hit)
- we have to recache at the web level, when all we really want to do is invalidate a memcached key

**Comment by bgracie** [comment]
Further issue:
- Tracy reports that she couldn't see David Lin even when she expanded the search
- is the livesearch_all_entries.js being cached as well?
- doesn't look like it at first blush:

Remote Address:141.101.126.83:443
Request URL:https://pathwaysbc.ca/livesearch_all_entries.js?_=1436912087426
Request Method:GET
Status Code:200 OK
Response Headers
cache-control:public, max-age=43200
cf-cache-status:MISS
cf-ray:20609522b9011b9d-SEA
content-encoding:gzip
content-type:text/javascript; charset=utf-8
date:Tue, 14 Jul 2015 22:14:48 GMT
etag:W/"467022384fd399321ff8a16c6fc65267"
expires:Wed, 15 Jul 2015 10:14:47 GMT
server:cloudflare-nginx
status:200 OK
status:200 OK
strict-transport-security:max-age=31536000
vary:Accept-Encoding
version:HTTP/1.1
via:1.1 vegur
x-rack-cache:miss
x-request-id:b943a343-fe6d-46c8-a279-6b8f2803a140
x-runtime:0.042063
x-ua-compatible:IE=Edge,chrome=1

**Comment by KelseyDH** [comment]
(in reference to #193 also)

The cache-control `max-age=43200` is from Cloudflare, as I've set Cloudflare our reverse proxy cache to cache assets for 12 hours (this can be configured by logging into cloudflare).  `'cf-cache-status: MISS' ` is also a reference to cloudflare (cf).  Cloudflare as a reverse proxy cache takes in all of our traffic and advances it to heroku, using HTTP caching to prevent unnecessary repeat requests.  I'm not sure browser cache misses is a major issue --- Cloudflare is conservative and only browser caches assets it can assure are truly static.

That said, all of this stuff is in reference to HTTP Browser caching, which will be completely different from our memcache server caching.

When it comes to memcache, the other area where an issue could possibly be occuring is from our Model caching (`Rails.cache.fetch`).  I've set all of them to either have no expiry, or to expire within 23 hours.  (The only exception is line 58 in city.rb where I call `Rails.cache.fetch([user.cache_key, specialization.cache_key], expires_in: 7.days)` for the method `self.for_user_in_specialization(user, specialization)`  -- however unless cities has changed for the user I don't see this being a problem.)

**Comment by bgracie** [comment]
need to also look into this email from Tracy

Hi Kelsey and Brian:

I have a note from our meeting on Tuesday, to send you a new email with regard to this issue (see forwarded email from December 17, below).  The same is true for Dr. Cathy Clelland.  She does not show up in the list of specialists on the left, nor is she searchable through the search box.  However if you go to "clinics" in Family Practice, and click on Primary Care-Community Maternity Centre (CMC), she is listed as one of the physicians working there and you can click on her from there, which takes you to her profile page.  As other divisions, including Vancouver, are now entering their own family physicians to Pathways, this will soon become a bigger issue.

Thanks for checking into this guys!
Tracy L.

---------- Forwarded message ----------
From: Tracy Lauridsen <tracy@pathwaysbc.ca>
Date: Wed, Dec 17, 2014 at 2:05 PM
Subject: Dr. Kim Shaw not showing up in list of Family Practice docs
To: "Dr. Ron Warneboldt" <thewarneboldts@gmail.com>
Cc: Russell Warneboldt <warneboldt@gmail.com>, Kelsey Hannan <khannan@pathwaysbc.ca>, Alanna Haggarty <alanna@pathwaysbc.ca>, Mary Anne Mattinson <mary_anne@pathwaysbc.ca>


As we discussed at yesterday's meeting, Dr. Kimberly Shaw does not show up in the list of Family Practice docs on Pathways, and she is not "searchable" through the search box.  However, when you go into Family Practice Clinics, and click on the link for the PCOC, she is listed as working there.  From there you can click on the link which takes you to her page.  

I believe she is not showing up in the list of "specialists" in Family Practice, because she does not have an address listed (no other office), other than her clinic association.  The other FP docs who have the blue arrow status in family practice, all have additional outside offices.

I think this is probably a "bug" associated with this new status "only accepts referrals through a clinic".  If you look under any other specialty, at the docs with the "other" blue arrow status "only works out of clinics or hospitals", they do not have an office address other than their clinic or hospital association.  And they still show up in the list of specialists.

Russell or Kelsey, could you check into this?  I know that we wanted to have the option to list an office outside of their clinic/hospital associations for Family Practice, but I don't think this should be required for them to show up in the listing.  

Hope that makes sense????
Thanks,

**Comment by bgracie** [comment]
- Karen reports that Zachary Schwartz (entered yesterday) still doesn't appear in Vancouver search box
- turns out there is a stale cache for vancouver entries search data
- either my recaching method is failing or the recache task is failing silently...

**Comment by bgracie** [comment]
see  https://github.com/pathwaysmedical/frasernw/pull/196
