### ISSUE TITLE
Change ordering of ortho AOP

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#211]
*Ankle

*Back

*Elbow

*Foot

*Hand

*Hip

*Knee

*Neck

*Shoulder

*Wrist

Braces and Splints

Casts

Hospital consultations in orthopedics

Joint aspiration

Joint Injection

Joint Viscosupplementation

Office consultations in orthopedics

Pediatric orthopedics (surgical/procedural)

WorkSafe BC (WSBC) cases

**Comment by KelseyDH** [comment]
Am I correct in saying we have fixed this with the changes to Joint Injection?  Wondering if we can close this now.

**Comment by bgracie** [comment]
No.  It refers to the ordering of the checkbox filters on the Ortho specialty page.  Pretty 'nice to have' and low priority IMO

**Comment by dhMuse** [comment]
Closed in favour of DEV#365.
