### ISSUE TITLE
CR: Delete deceased physicians from the Pathways database after 2 years

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#223]
For this we just need a rake task to spot specialists with a deceased status who have `updated_at` timestamps older than 2 years.  The rake task can be added to our clockwork rake tasks, ideally after a database backup.

November 2015, CR 1. Priority 1

**Comment by bgracie** [comment]
**Possible implementation 1:**
- we rely on Versions to tell us when their status mask was changed to `deceased`
- potential issue: this only tells us when their PW entry was updated as deceased, not when they actually passed away

**Possible implementation 2:**
- we put a field `passed_away_on` on `specialist`
- potential issue: we might not know when they passed

**Possible implementation 3**
- start with `1`, and if it's deemed necessary to be more precise, add `2`

**Comment by KelseyDH** [comment]
@bgracie Yeah I was thinking of just linking it to the `deceased` status_mask whenever `specialist.updated_at` is less than two years.  Only downside of this is that if you make a migration updating the Specialists table within those two years, the updated_at timestamp won't accurately remove the deceased specialist.

RE implementation 2, I don't think we need to worry about tracking *the date of death*.  It's a burden on data entry to ask for it, and in practical terms there is supposed to be two years of display for the record until it's removed from the site (we don't want a specialist who died more than two years ago to be immediately deleted if their status is only recently updated to reflect this, as one reason for the two year grace period is to slowly inform users who might be looking for that doctor that the doctor is now deceased)

However, a modified verson of implementation 2 where we add a `updated_to_deceased_at` field to specialist that records `Date.now` to that field whenever a status is made to deceased could get around the issue with Versions.

**Comment by KelseyDH** [comment]
Since we're deleting data it may also be a good idea to have the system notifer email us whenever a specialist gets deleted through this route just to make sure we catch any bugs related to accidental deletions of data.

**Comment by bgracie** [comment]
If I'm not mistaken, I can reliably infer date of update to deceased from `versions`, so there shouldn't be a need to add another db field.  Notify when the deletion happens is not a bad idea for now as well...

**Comment by KelseyDH** [comment]
Commit for ref: 04348b84977060e50de8e1b9ea3fd725cde9fc7a
