### ISSUE TITLE
CR:  Make resources more easily shareable to other Divisions

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#226]
CR 5. November 2015.  Priority 1b.

From CR:  "Within a notification notice provide the ability to easily add the new resource to the notification recipient's division."

**Comment by bgracie** [comment]
extended in CR#21: we need to implement a link in the 'new resource' notification email which shares all of the resources to the division.

**Comment by KelseyDH** [comment]
@bgracie  Likely going to do this within an interface on Pathways rather than on email.

**Comment by bgracie** [comment]
why?

**Comment by KelseyDH** [comment]
Building a share interface into the email message itself has security risks, is a large mental overheard and the problem can be solved in easier/better ways.  Modifying the email to point the user to a resource handling interface within Pathways is really what was articulated as wanted at last night's UG.

**Comment by bgracie** [comment]
I actually asked for clarification on the last point, and it seemed like the preferred option was within the email.  What's the security risk if PW checks that the user is logged in?

**Comment by KelseyDH** [comment]
Part of the problem with email is there is no feedback functionality.  They get a list of notifications and things they want to share in various emails but no feedback as to what has been or hasn't been shared.  Ditto also if they miss emails.  Even if we build it this why they will likely still want a similar listing format within Pathways itself.

I think as long as we build an interface in a list like format that lists with checkboxes recent resources and the ability to bulk share they will be happy.

RE:  security.  The issue is that having the action actually trigger through sharing requires some token mechanism within the link.  If we expire them that can confuse people, if we don't, then outsiders who get access to emails could click these email token links to trigger actions.  It makes far more sense for us to design the functionality inside the application but make it easy for people to reach it when emails are sent.

**Comment by bgracie** [comment]
well, here's what I envision with the bulk share through email flow:

- user gets notification email
- they click on "add all to my division" within the email
- if they're logged in, they get a confirmation page: "the following resources have been added to your division"
- if they're not, they're prompted to login first, and then they get the confirmation page
- no token is required

I really think this is the way to go b.c. it's dead simple, even implementation....

**Comment by KelseyDH** [comment]
One problem with this is due to how the notification system is designed.  If I remember correctly, notifications sent out via intervals are defined only by whatever settings people create for them, so you can have the same notification get sent to somebody on a daily or weekly basis.

Though I guess if the default behaviour is to just check whether something is already shared or not repeated sharing would not be an issue.

(It does mean we'll likely need a notification interface regardless, which we have right now at pathwaysbc.ca/notifications )
