### ISSUE TITLE
CR:  Secret Edit Links: Add the name of the person who sent out a secret edit link in a 'notes type/ history' field & add functionality to cancel secret edit link & regenerate a new one if necessary.

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#229]
CR 6. November 2015. Priority 1b.

This feature is to give us better security control over how access links are given out and administered.

**Comment by bgracie** [comment]
Specs:
- [ ] automated recache functions as expected
- [ ] admins can generate tokens for specialists/clinics for which they have edit privileges
- [ ] super admins can generate tokens for all specialists and clinics
- [ ] admins can expire their own tokens
- [ ] super admins can expire all tokens
- [ ] admins can expire tokens created by users who no longer are admins
- [ ] in token creation interface, admin must specify recipient before token is created
- [ ] in specialist/clinic history, new history entries specify editor (derived from token recipient)
- [ ] in specialist/clinic history, new history entries specify token creator

**Comment by bgracie** [comment]
https://github.com/pathwaysmedical/frasernw/commit/b304edaaf04174b61d7ce949c8c3b694b2356959
