### ISSUE TITLE
fix specialists' 'responded to survey' being tied to search behaviour

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#235]
- `only works out of hospitals or clinics` should not be a categorization... the other information on the form already tells us where they work; let's use it

**Comment by KelseyDH** [comment]
I think this status is used to imply that they do not accept referrals directly, but rather the referral needs to go through the hospital or clinic instead.  There is some logic tied up to this categorization if I'm not mistaken in terms of how we present specialists in the view, so any change here needs to be carefully considered.

**Comment by bgracie** [comment]
I agree.  Need to figure out why it was made like that in the first place.

**Comment by KelseyDH** [comment]
One reason for the categorization is that a Specialist can be linked to a Hospital or a Clinic *while* accepting referrals, but they can also *only* work out of a hospital or clinic.  You'll notice that when this categorization option is selected that location information for the Specialist is hidden, and they can only be linked to an existing link of Hospitals/Clinics.

Any investigation into this should probably also tackle bug #212

**Comment by dhMuse** [comment]
Obsolete.
