### ISSUE TITLE
Hospital: filter checkboxes breaking the filter view

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#244]
To replicate:  Go to https://pathwaysbc.ca/hospitals/8 and try checking Addiction Medicine.  The filter view breaks when this is attempted.

**Comment by KelseyDH** [comment]
JS error in console is:  `Uncaught ReferenceError: table_data is not defined`

**Comment by dhMuse** [comment]
Obsolete by new filter system.
