### ISSUE TITLE
Make Pathways emails pretty

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#262]
Currently we just send plaintext emails but it would be nice to have our emails have a nicely formatted template with Pathways branding instead.  There are ruby gems that can take external CSS stylesheets and convert them to become inline css for emails so that we don't need to use custom mark up for each email.

**Comment by dhMuse** [comment]
Closed by 9a75532c920a32c1cd4891e63c368fed9d580451 (which looks to be squashed in 1a64921372961e37ba2da8b2596096f4b85e7eb8).
