### ISSUE TITLE
History should identify who wrote feedback items, or link correctly to feedback items so they can be found in the archived feedback queue

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#273]

**Comment by KelseyDH** [comment]
Or alternatively we have history show the email of the user who sent the feedback.

**Comment by dhMuse** [comment]
CR 28: Update History so that links to feedback queues direct to the exact feedback item.

**Comment by dhMuse** [comment]
Closed in favour of CR#28.
