### ISSUE TITLE
Add suffix labels to:  Midwife, Internal Medicine, Nurse Practitioner and Family Physicians

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#276]
Extension of existing GP labels, but for other specializations.  Should appear after name.  E.g. `John Smith` **GP**

**Comment by KelseyDH** [comment]
Finished, but follow up for Internal Medicine in progress.

**Comment by bgracie** [comment]
Internal medicine suffix will be added in on a case by case basis

- criteria: they have a fellowship in int. med but no subspecialties

**Comment by KelseyDH** [comment]
I think we settled on just adding a checkbox for Internal Medicine to decide on a case by case basis?

**Comment by KelseyDH** [comment]
Waiting feedback on new version.
