### ISSUE TITLE
Clinic unavailable_from date still saves form value even if status "permanently closed" is not selected

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#280]
This has no real effect other than creating messy data entry as it still saves a version.  Basically if someone checks `permanently closed` then radios back to `Accepting new referrals`, the date field that gets saved for "unavailable_from" still saves.  I suspect this is occuring in other form fields whenever they get dynamically updated.

**Comment by KelseyDH** [comment]
Part of the problem with fixing this is that the opposite behaviour could be more damaging.  Section blanking form fields when a radio button is unselected is not ideal behaviour.  One way to fix this would be to dynamically scrub params at the controller level like how Subscriptions Controller does it: https://github.com/pathwaysmedical/frasernw/blob/14fa76f0e68a1a609189dc46a5b076d072b784a6/app/controllers/subscriptions_controller.rb#L89, but this is pretty messy and this kind of logic could become very unwieldy over a large form like Specialist / Clinic forms are.

Given this isn't actually causing problems I'm tempted to just ignore this issue.

**Comment by dhMuse** [comment]
Revisit as needed.
