### ISSUE TITLE
Modify referral forms to allow easy linking and unlinking of any form to any specialist or clinic. 

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#284]
Recommendation coming out of our investigation of expanding stubbed Specialist pages (CR 24 / Github issue #256)

**Comment by KelseyDH** [comment]
When this is done, `Entity Page Views` in _Reports_ will probably need to be updated so that reports about referral forms link to a general show page rather than a specific clinic or specialist for that form.

**Comment by KelseyDH** [comment]
Due to possible changes to Referral Forms this change is low a priority 4.

**Comment by dhMuse** [comment]
Closed in favour of CR#29.
