### ISSUE TITLE
Modify specialty pages to preserve tab position (e.g. specialist/clinic/patient info) when users hit the back button

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#287]
E.g. when people hit the Clinics tab and open a clinic and then go back, the server reloads the user's last page, but does not preserve where on the previous page they were.

Probably requires looking into a React routing library.

**Comment by KelseyDH** [comment]
Commit on this issue:  503be179e84e67e5e1

**Comment by bgracie** [comment]
Modify react app to be component-based rather than page-based:

- [ ] Nav Tabs
- [ ] Sidebar
- [ ] Main Panel
- [ ] Table
- [ ] Inline Articles
- [ ] List
- [ ] Main Panel Title
- [ ] Main Panel Subtitle

**Comment by dhMuse** [comment]
Closed in favour of CR#30.
