### ISSUE TITLE
Fix DB backups after heroku broke their api

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#290]

**Comment by bgracie** [comment]
- we still have pg:backups running daily at 8:00 UTC, so this is not an urgent issue

**Comment by KelseyDH** [comment]
Yeah I did that just as an immediate measure, however it's not safe to only rely on pg:backups to hold our backups.  I don't know how long they hold backup snapshots for us, and furthermore it only takes one error on our end or their end for us to lose this data.

For data as expensive as ours to maintain, we can't settle for anything less than the 3-2-1 rule.

**Comment by bgracie** [comment]
Okay, yeah this works now.
