### ISSUE TITLE
expand specialists who "only work out of hospitals or clinics"

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#293]
- on test site now
- potentially deploy Saturday, Jan 30th

**Comment by KelseyDH** [comment]
Follow up from #256.

Feedback from the User Group for the current design is positive, however Kathleen and others indicated a preference towards reducing the size of each Clinic section shown, with the ability to expand the section within the page to see contact info using an accordian style interface if that was the referral choice desired.

**Comment by KelseyDH** [comment]
Russell's first mockup was deployed with last week's integration on the "expanded_works_out_of" branch.  Still some discussions on the final design e.g. #316
