### ISSUE TITLE
updates to specialist offices & clinic locations being lost

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#298]
to reproduce:

- secret edit a specialist
- switch a 'not used' location to 'in an office', and enter a phone number
- when the form is reviewed, location will still initially be 'not used'
- when you switch it to 'in an office', you will see the orange annotation that phone 'was blank', but the new value doesn't appear in the field

Clinic locations have the same problem.

**Comment by KelseyDH** [comment]
Pending no issues in testing this looks good. :+1:
