### ISSUE TITLE
Specialist#cities and related methods have to be recached every night before latest updates

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#310]
Since that's not the case currently, we're getting old 'cities' sometimes when we generate latest updates

In general, you should always be able to `force` regeneration of cached method results easily.  In fact, Rails makes this easy for you:

```
def cities(force: false)
    result = Rails.cache.fetch([self.class.name, self.id, "cities"], force: force) do
      if responded?
        citees = offices.map{ |o| o.city }.reject{ |c| c.blank? }.uniq
      elsif hospital_or_clinic_only?
        citees = (hospitals.map{ |h| h.city } + clinics.map{ |c| c.cities }).flatten.reject{ |i| i == nil }.uniq
      elsif not_responded? || purposely_not_yet_surveyed? || hospital_or_clinic_referrals_only?
        (offices.map{ |o| o.city } + hospitals.map{ |h| h.city } + clinics.map{ |c| c.cities }).flatten.reject{ |c| c.blank? }.uniq
      else
        []
      end
    end
    return result.is_a?(NullData) ? nil : result
  end
```

**Comment by bgracie** [comment]
fixed in https://github.com/pathwaysmedical/frasernw/commit/7dc9b292095b724d1a85bd7776236a0562fcbe22

**Comment by KelseyDH** [comment]
@bgracie  Is there are reason you got rid of the NullData object in 7dc9b29 ?  Without it for memcache any result that returns `nil` will require a expensive hit to the database each time.

**Comment by KelseyDH** [comment]
Otherwise adding the ability to force this sounds like a good idea
