### ISSUE TITLE
NameError in environment

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#325]
## New exception in pathways

**NameError** in **environment**
uninitialized constant Pry

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/56c43cfbc02c215385fb2005?event_id=56c43cfc67a83f623b6774e0)

## Stacktrace

    config/initializers/pry.rb:1 - <top (required)>
    config/environment.rb:5 - <top (required)>
    lib/tasks/assets.rake:11 - block (2 levels) in <top (required)>

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/56c43cfbc02c215385fb2005?event_id=56c43cfc67a83f623b6774e0)

**Comment by bgracie** [comment]
@KelseyDH there's no way this is happening in production.  That initializer isn't deployed there yet.

**Comment by KelseyDH** [comment]
Yeah ByeBug's API is getting called from either you or my dev machine having Bugsnag's ENV variables.  Now that it's working again I guess they are getting submitted.

**Comment by KelseyDH** [comment]
Make sure in your env file you have this set `ENV['BUGSNAG_ENABLED'] = 'false'` otherwise config/initializers/bugsnag.rb will be active.
