### ISSUE TITLE
ActionView::Template::Error in reports#show

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#327]
## New exception in pathways

**ActionView::Template::Error** in **reports#show**
undefined method `focused?' for nil:NilClass

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/56c52091c02c215385ffb570?event_id=56c520914819bac61e01c6db)

## Stacktrace

    app/views/reports/stats.html.haml:53 - block in _app_views_reports_stats_html_haml__1059182132452561253_69839530620780
    app/views/reports/stats.html.haml:53 - reject
    app/views/reports/stats.html.haml:53 - _app_views_reports_stats_html_haml__1059182132452561253_69839530620780
    app/controllers/reports_controller.rb:126 - show

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/56c52091c02c215385ffb570?event_id=56c520914819bac61e01c6db)

**Comment by KelseyDH** [comment]
Fixed with ea011193f234c48777, thanks @bgracie
