### ISSUE TITLE
NoMethodError in divisions#create

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#329]
## Error in pathways

**NoMethodError** in **divisions#create**
undefined method `super_admin?' for nil:NilClass

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/56c60c55c02c21538503f5f3?event_id=56c60c55cf437e7c21b5b01e)

## Stacktrace

    app/controllers/divisions_controller.rb:51 - block in create
    app/controllers/divisions_controller.rb:47 - each
    app/controllers/divisions_controller.rb:47 - create

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/56c60c55c02c21538503f5f3?event_id=56c60c55cf437e7c21b5b01e)

**Comment by bgracie** [comment]
This was because a FNW specialization option didn't have an owner, so I've fixed the immediate problem by assigning one.  We have to make sure that in the future specialization options don't get created without owners, however.
