### ISSUE TITLE
NoMethodError in jobs:work

### ISSUE THREAD

**Issue by pathwaysmedical** [pathwaysmedical/frasernw#330]
## Error in pathways

**NoMethodError** in **jobs:work**
undefined method `open_to_sc_category?' for nil:NilClass

[View on Bugsnag](https://bugsnag.com/pathways/pathways/errors/56a21398c02c2153856335fa?event_id=56c6631643d82cca084c00ea)

## Stacktrace

    app/domain/serialized.rb:268 - open_to_panel
    app/domain/serialized.rb:254 - block (2 levels) in call
    app/domain/serialized.rb:253 - each
    app/domain/serialized.rb:253 - inject
    app/domain/serialized.rb:253 - block in call
    app/domain/serialized.rb:246 - each
    app/domain/serialized.rb:246 - inject
    app/domain/serialized.rb:246 - call
    app/domain/serialized.rb:17 - generate
    app/domain/serialized.rb:23 - regenerate
    bin/rake:37 - <main>

[View full stacktrace](https://bugsnag.com/pathways/pathways/errors/56a21398c02c2153856335fa?event_id=56c6631643d82cca084c00ea)

**Comment by bgracie** [comment]
Fixed here https://github.com/pathwaysmedical/frasernw/commit/102165626cbd7925d7b2a3d042e3b47a2c748c5e
