### ISSUE TITLE
Hide Access Keys in the Users table (e.g. Pending Accounts) so that admins need to click to reveal them

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#339]
Right now the Users#index table shows access keys for each user in Pending Accounts.

This raises the risk that if this table is printed or copied by an admin, access key values could be leaked outside of Pathways.

So as a security measure, we should hide access key values with a "Show" link for admins to click if they want to see the value for one.

---

This idea is still being run by admin's to see if they approve of it, as it will make their work a little more inconvenient.

**Comment by dhMuse** [comment]
Revisit upon request.
