### ISSUE TITLE
add status dropdown to "only works out of hospitals and clinics"

### ISSUE THREAD

**Issue by KelseyDH** [pathwaysmedical/frasernw#351]
A request that came from #256 that would prevent needing to relabel specialists who are retiring to "responded to survey" in order to give them this status.

**Comment by bgracie** [comment]
'status' should be broken into:
- accepting new referrals?
- accepts referrals through hospitals and clinics?
- referrals limited by geography or # of patients?
- 'availability' -- includes 'retired, unavailable, deceased, etc'

**Comment by bgracie** [comment]
- [ ] specialist.rb
- [ ] specialists#show
- [ ] specialists form
- [ ] clinic.rb
- [ ] clinics#show
- [ ] clinics form
- [ ] serialized indices
- [ ] filter table

**Comment by bgracie** [comment]
- so we need 'only works out of hospitals and clinics' as a different data point from attendances, offices, privileges?

**Comment by bgracie** [comment]
- add 'doing followup' as a field?

**Comment by bgracie** [comment]
- when to show "GP doing follow up at office"?

**Comment by bgracie** [comment]
- phone schedule, website, etc, is currently on specialist office, not office
- why? presumably if two specialists share the same office they will have the same phone schedule..
- is the phone schedule for the office phone (MOA) or physician?

**Comment by bgracie** [comment]
- in the case of website, seems like they're either likely to have a personal site for all their work or share a site for the office?

**Comment by dhMuse** [comment]
Closed in favour of DEV#62.
