### ISSUE TITLE
investigate switching to puma

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#360]
- looks like we can get significant speed and memory usage improvements, even on MRI

http://puma.io/
https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server
http://www.mikeperham.com/2012/12/12/12-gems-of-christmas-1-puma/

**Comment by bgracie** [comment]
I didn't try this yet, but Kelsey did.  He ran into problems and had to revert.  Proceed with caution.

**Comment by dhMuse** [comment]
Closed in favour of DEV#370.
