### ISSUE TITLE
improve process for updating demo site

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#362]
- right now, blocks our workflow locally too much
- build on cloud vm?
- integrate into main deployment?
- also, the masking system could be more straightforward: simple 1/1 correspondence between attribute and faker
- standardize process for updating the seed creator in responses to changes in schema (maybe programmatic requirement to handle every attribute?)

**Comment by dhMuse** [comment]
Closed in favour of DEV#360.
