### ISSUE TITLE
support internet explorer 9

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#372]
and remove the 'old browser' warning for it

**Comment by dhMuse** [comment]
Probably we support IE9 already without a hitch.
Three areas of possible concern:
- Styling maximums
   - [Explained here](http://stackoverflow.com/questions/12126118/rails-asset-pipeline-solution-for-ie-4096-selector-stylesheet-limit)
   - [Microsoft's advice](https://support.microsoft.com/en-us/kb/262161)
   - [One potential solution to this limit](https://www.foraker.com/blog/rails-asset-pipeline-handling-of-css-and-js)
- Strict JSON standards, [as described floridly here](http://rob.conery.io/2011/10/24/a-fun-little-json-murder-mystery-with-ie9/)
- Various security issues, [as specified by browser here](https://html5sec.org/)

For reference: [Microsoft's relevant support policy](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support)
