### ISSUE TITLE
Extend concept of local referral area

### ISSUE THREAD

**Issue by warneboldt** [pathwaysmedical/frasernw#46]
Rural divisions want to be able to sort their "very local" cities above distance cities in their "local referral area". Suggest that cities can be given a "priority" when the local referral area is defined, which will control sorting, perhaps a number from 1 (high) to 5 (low), with a default of all cities getting 5.

**Comment by KelseyDH** [comment]
Proximity sorting by city is now available to rural areas with the new Specialty filter table.
