### ISSUE TITLE
Reporting System Upgrade: Google Analytics

### ISSUE THREAD

**Issue by warneboldt** [pathwaysmedical/frasernw#54]
Get some better gem for the Google Analytics API than we currently have. Or possibly fix the current one. I might just be doing it wrong.

**Comment by bgracie** [comment]
[Preliminary List of Web Variables.pdf | uploaded via ZenHub](https://files.zenhub.io/5550f75ad40187b7722fd0dc)

**Comment by KelseyDH** [comment]
Closing this now that we have the new Reporting dashboard.
