### ISSUE TITLE
Investigate / fix why "locations" sometimes rearrange themselves for specialists / clinics

### ISSUE THREAD

**Issue by warneboldt** [pathwaysmedical/frasernw#64]
Sometime something that was in "Location 1" seems to jump to "Location 2" or "Location 3"

**Comment by KelseyDH** [comment]
Location in Clinic/Edit form are flipping around (Clinic 365 one, Clinic 745).  Location 5, 6 or 9 are common positions but the position is random.

**Comment by KelseyDH** [comment]
Will be assigning this to Brian.

**Comment by bgracie** [comment]
Specs:
- clinic locations should always appear in the same order
- clinic locations with data should appear before those without data
- the form should update the relevant records properly

**Comment by KelseyDH** [comment]
:+1:

**Comment by warneboldt** [comment]
Small note: user accounts can be linked to locations, when giving users permission to edit specialists or clinics. So, if programmatically rearranging locations, the potential for this association needs to be kept in mind. 

This is also why having administrators manually rearrange locations via copy/paste can wreak havoc on the system, as the user-to-locations permissions can be broken.

**Comment by KelseyDH** [comment]
Thanks Russell, Brian's PR fix in #127 doesn't appear to change anything about how the underlying objects are handled on the form, so I don't think we will have problems. since Clinic locations that are empty will just be displayed differently in the form view now.

**Comment by warneboldt** [comment]
Sounds good. The only other thought I have is to ensure my somewhat questionable JavaScript code for the self-edit "review queue" reviews still works, where it walks the serialized object and compares / highlights the changes the specialist or clinic user has made against the original, live, record.
