### ISSUE TITLE
Give ability to reorder locations for specialists / clinics

### ISSUE THREAD

**Issue by warneboldt** [pathwaysmedical/frasernw#65]
Location rearranging through copy / paste is both slow and error prone, but it can also introduce issues where we have linked certain users to specific specialist / clinic locations, which are now "swapped" through a data swap, not a linkage swap.

We want to be able to rearrange the locations in a way that is both faster, and preserves the linkages to "users that can edit this specialists / clinic". This probably will require some sort of "sort order" for locations to be stored.

Possibly relies on #64 to be fixed.

**Comment by KelseyDH** [comment]
@bgracie May want to considered giving this a look to see if this is resolved after your work on #64

**Comment by dhMuse** [comment]
Closed in favour of CR#14.
