### ISSUE TITLE
Modify specialist form that is sent out via review queue system to be "short form"

### ISSUE THREAD

**Issue by warneboldt** [pathwaysmedical/frasernw#86]

**Comment by KelseyDH** [comment]
I might need a little clarification on what this task is looking for.

**Comment by KelseyDH** [comment]
@warneboldt  Closing this unless you still think this is an issue.

**Comment by warneboldt** [comment]
The user group had approved a few changes to the form that goes out via the review queue, to simplify workflow for users:

- It shouldn't allow users to change their categorization (as this is just confusing for them)
- It shouldn't allow users to change their specialty/specialties, which is good for a few reasons: 
(a) the list of areas of practice doesn't update until a subsequent save + edit form, which can't be done easily during the review queue flow (b) specialists won't be confused between areas of specialty vs. areas of interest / focus
- Address editing is a constant source of confusion; instead we wanted to simply show them their addresses, and provide a free-form box that basically says "if you have any updates to your address(es), enter them here:"

The idea then is that an Admin could enter as little as a name and specialty, and then send out a form to an office to complete the rest.
