### ISSUE TITLE
Typing 'injection' into search gives a lot of 'Fluoroscopy MSK' injections, but no joint injections. 

### ISSUE THREAD

**Issue by warneboldt** [pathwaysmedical/frasernw#93]
Can this be improved? Perhaps grouping sub areas of practice better? Perhaps using length of search key to match?

**Comment by KelseyDH** [comment]
Interestingly "injectio..." still has good results, this only happens when "injection" is fully typed.  Hopefully users catch it before then, but I agree still not ideal for "injection" to have this.

**Comment by dhMuse** [comment]
Closed in favour of REQ#164.
